# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 

container: "library://kevinrue/cncb/cncb-2:latest"

configfile: "config/config.yaml"

genome_fastqs_noext = [file.replace('.fq.gz', '') for file in config['genome']['fastqs']]

##### load rules #####

include: "alevin.smk"
include: "common.smk"
include: "genome.smk"
include: "genome_qc.smk"

##### main rule #####
rule all:
    input:
        "results/genome/alternate_reference.merged.fa.gz",
        "qc/genome/multiqc/multiqc_report.html",
        "resources/genome/index/alevin",
