# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 

container: "library://kevinrue/cncb/gatk4:latest"

configfile: "config/config.yaml"

##### load rules #####

include: "genome.smk"

##### main rule #####
rule all:
    input:
        # gatk index
        "resources/genome/genome.dict",
        "resources/genome/genome.fa.gz.fai",
        "resources/genome/genome.fa.gz.gzi",
        # bwa index
        "resources/genome/genome.fa.gz.amb",
        "resources/genome/genome.fa.gz.ann",
        "resources/genome/genome.fa.gz.bwt",
        "resources/genome/genome.fa.gz.pac",
        "resources/genome/genome.fa.gz.sa",
        #bwa mem
        "resources/genome_resequencing/mapped.bam",
